update oc-admin code

diff --git a/lrctl b/lrctl
--- a/lrctl
+++ b/lrctl
@@ -12,6 +12,10 @@ lrctl_version="6.5.5"
 lrctl_image=""
 lrctl_new_shell_after_group_membership=1
 lrctl_docker_membership_return_code=255
+ocdb_repo="gcr.io/lrcollection"
+ocdb_version="6.0.1"
+ocadmin_repo="gcr.io/lrcollection"
+ocadmin_version="6.0.4"
 
 lrctl_volume_mounts=()
 # Expose the hosts Docker socket to the container.
@@ -594,6 +598,447 @@ processVersionsInfo() {
 
 }
 
+ocdbContainerStart(){
+  echo "### Create/Start OC-DB (\`oc-db\`) container for PostgreSQL using \`oc-db\` Volume..."
+  docker run --network logrhythm --env POSTGRES_PASSWORD=`date --rfc-3339=ns | md5sum | cut -c-32` --name oc-db --volume oc-db:/var/lib/postgresql/data --detach ${ocdb_repo}/oc-db:${ocdb_version}
+  
+  sleep 5
+  echo "done"
+}
+
+# === EZ OC Start ===
+
+#=====Initializing OC admin and start ===
+function initializingOcDB() {
+  echo "start initializing DB"
+  strongPassword=false
+  countUser=$( docker exec -i oc-db psql --username=postgres --dbname oc-admin -c "select count(*) from public.\"rbacUserToRole\";"  || true )
+  echo $countUser
+
+  rm -rf ocdbDir 2> /dev/null
+  mkdir -p ocdbDir 2> /dev/null
+  cd ocdbDir
+  CONTAINER_DB_FILE_BASE="/app/database/pgsql"
+  #GITHUB_REPO_URL_BASE="https://raw.githubusercontent.com/logrhythm/versions/EZCloud"
+  DB_CREATION_SCRIPT=""
+  if [ "$1" == "start" ]
+  then
+    DB_CREATION_SCRIPT="create_database.sh"
+  else
+    DB_CREATION_SCRIPT="reset_ocAdmin_password.sh"
+  fi
+
+  echo ""
+  echo "Please provide a password for the default user ocAdmin."
+  echo "Or press [CTRL]+[C] to abandon."
+  echo ""
+  echo "Rules:"
+  
+  # Prompt for pass if `OC_ADMIN_PASSWORD` isn't already set with at least a 6 character long password
+  # And keep looping until a 6+ character long password is provided, or user press CTRL+C
+  # Password verification is prompted to make sure the user knows which password it is, unlike Brandon Pace
+  PASSWORDS_DIDNT_MATCH=0
+  until false
+  do
+    if [[ $PASSWORDS_DIDNT_MATCH -eq 0 ]]
+    then
+      OC_ADMIN_PASSWORD_ONE=""
+      until false
+      do 
+        if [ ${#OC_ADMIN_PASSWORD_ONE} -gt 5 ]
+        then
+          break
+        else
+          echo " - Password should have a mix of lowercase, uppercase, number and signs/non-alphanumerical(?,#,@,!,$,&,%) characters"
+          echo " - Password must have a minimum of 6 characters"
+          echo ""
+          read -sp 'Password: ' OC_ADMIN_PASSWORD_ONE </dev/tty
+          echo ""
+          echo ""
+          
+        fi
+      done
+
+      strongPassword=false
+      len="${#OC_ADMIN_PASSWORD_ONE}"
+
+      if test $len -ge 6 ; then
+
+          echo "$OC_ADMIN_PASSWORD_ONE" | grep -q [0-9]
+
+          if test $? -eq 0 ; then
+
+                echo "$OC_ADMIN_PASSWORD_ONE" | grep -q [A-Z]
+
+                      if test $? -eq 0 ; then
+
+                          echo "$OC_ADMIN_PASSWORD_ONE" | grep -q [a-z]
+
+                            if test $? -eq 0 ; then 
+
+                              echo "$OC_ADMIN_PASSWORD_ONE" | grep -q '[]:/?#@!$&'"'"'()*+,;=%[]'
+
+                                if test $? -eq 0 ; then
+                                  strongPassword=true
+                                  echo "Strong password"
+                            
+                                else
+                                  strongPassword=false
+                                  echo "weak password. Please include special chars"
+                                
+                                fi                       
+      
+                            else
+                              strongPassword=false
+                              echo "weak password. Please include lower case char"
+
+                            fi
+                        else
+                          strongPassword=false
+                          echo "weak password. Please include capital char" 
+
+                      fi
+                else
+
+            echo "weak password. Please include numbers"   
+
+          fi
+
+      else
+          strongPassword=false
+          echo "weak password. Please enter a password with a minimum of 6 characters"
+
+      fi
+
+      #if [[ ${#OC_ADMIN_PASSWORD_ONE} -ge 6 && "$OC_ADMIN_PASSWORD_ONE" == *[A-Z]* && "$OC_ADMIN_PASSWORD_ONE" == *[a-z]* && "$OC_ADMIN_PASSWORD_ONE" == *[0-9]* ]] && [[ ! "$OC_ADMIN_PASSWORD_ONE"  =~ ^[a-zA-Z0-9]+$ ]]
+      if $strongPassword
+      then
+        read -sp 'Please re-enter to verify: ' OC_ADMIN_PASSWORD_TWO </dev/tty
+        echo ""
+        echo ""
+        if [ "$OC_ADMIN_PASSWORD_ONE" = "$OC_ADMIN_PASSWORD_TWO" ]; then
+          OC_ADMIN_PASSWORD="$OC_ADMIN_PASSWORD_ONE"
+          PASSWORDS_DIDNT_MATCH=1
+        else
+          echo "Error: Passwords do not match. Please try again."
+          PASSWORDS_DIDNT_MATCH=0
+        fi
+        OC_ADMIN_PASSWORD_ONE=""
+        OC_ADMIN_PASSWORD_TWO=""
+      else
+        PASSWORDS_DIDNT_MATCH=0
+        OC_ADMIN_PASSWORD_ONE=""
+        OC_ADMIN_PASSWORD_TWO=""
+      fi
+    else
+      break
+    fi
+  done
+
+  unset OC_ADMIN_PASSWORD_ONE
+  unset OC_ADMIN_PASSWORD_TWO
+
+  # Create a clean folder
+  echo "### CREATING A CLEAN DIRECTORY (\`./pgsql\`)..."
+  mkdir -p pgsql 2> /dev/null
+  # Clean up
+  rm -f pgsql/create_database.sh 2> /dev/null
+  rm -f pgsql/*.sql 2> /dev/null
+
+  echo "### WALK IN \`./pgsql\` DIRECTORY..."
+  cd pgsql
+
+  # Get the DB creation files
+  echo "### DOWNLOADING \"$CONTAINER_DB_FILE_BASE/$DB_CREATION_SCRIPT\"..."
+  docker exec -i oc-admin cat "$CONTAINER_DB_FILE_BASE/$DB_CREATION_SCRIPT" > "$DB_CREATION_SCRIPT"
+  if [ "$1" == "start" ]
+  then
+    echo "### PARSING \"$DB_CREATION_SCRIPT\" TO DISCOVER FILES TO DOWNLOAD..."
+    IFS=$(echo -en "\n\b")
+    for SQL_FILE_NAME in $(cat $DB_CREATION_SCRIPT | grep --only-matching "^\\s*cat\\s\+\"[0-9]\+[^\|]\+"  | grep --only-matching "\"[^\"]\+\"" | grep --only-matching "[^\"]\+")
+    do
+        echo "### DOWNLOADING \"$CONTAINER_DB_FILE_BASE/$SQL_FILE_NAME\"..."
+        docker exec -i oc-admin cat "$CONTAINER_DB_FILE_BASE/$SQL_FILE_NAME" > "$SQL_FILE_NAME"
+    done
+  else
+    SQL_FILE_NAME="20220819. - Reset OCAdmin Password.sql"
+    docker exec -i oc-admin cat "$CONTAINER_DB_FILE_BASE/$SQL_FILE_NAME" > "$SQL_FILE_NAME"
+  fi
+
+  echo "### RUN DATABASE CREATION SCRIPTS..."
+  chmod +x "$DB_CREATION_SCRIPT"
+  # Environment variable `OC_ADMIN_PASSWORD` will be used to create the `ocAdmin` user
+  export OC_ADMIN_PASSWORD
+  bash "$DB_CREATION_SCRIPT"
+  # Clear OC_ADMIN_PASSWORD
+  unset OC_ADMIN_PASSWORD
+  cd ..
+  sleep 5
+  echo "Password set for user ocAdmin."
+
+}
+
+function cleanOcDbImages() {
+  DOCKER_IMAGE_IDS=$( docker images | grep "oc-db" | awk '{print $3}' )
+  if [ -z "$DOCKER_IMAGE_IDS" -o "$DOCKER_IMAGE_IDS" == " " ]; then
+    echo "---- No images available for deletion ----"
+  else
+     docker rmi -f $DOCKER_IMAGE_IDS
+  fi
+}
+
+function cleanOcDbContainer() {
+  DOCKER_CONTAINER_IDS=$( docker ps -a -q -f name="oc-db" )
+  if [ -z "$DOCKER_CONTAINER_IDS" -o "$DOCKER_CONTAINER_IDS" == " " ]; then
+    echo "---- No Container available for deletion ----"
+  else
+     docker rm -f $DOCKER_CONTAINER_IDS
+  fi
+}
+
+function cleanOcAdminImages() {
+  DOCKER_IMAGE_IDS=$( docker images | grep "oc-admin" | awk '{print $3}' )
+  if [ -z "$DOCKER_IMAGE_IDS" -o "$DOCKER_IMAGE_IDS" == " " ]; then
+    echo "---- No images available for deletion ----"
+  else
+     docker rmi -f $DOCKER_IMAGE_IDS
+  fi
+}
+
+function cleanOcAdminContainer() {
+  DOCKER_CONTAINER_IDS=$( docker ps -a -q -f name="oc-admin" )
+  if [ -z "$DOCKER_CONTAINER_IDS" -o "$DOCKER_CONTAINER_IDS" == " " ]; then
+    echo "---- No Container available for deletion ----"
+  else
+     docker rm -f $DOCKER_CONTAINER_IDS
+  fi
+}
+
+processStartOC_DB(){
+  
+  isOcDbVolume=false
+  volumes=$(docker volume ls  --format '{{.Name}}')
+  for volume in $volumes
+  do
+    if [ "$volume" == "oc-db" ]
+    then
+      isOcDbVolume=true
+    fi
+  done
+
+  if $isOcDbVolume 
+  then
+		isOcDbcontainer=$( docker ps -q -f name='oc-db' )
+		
+		if [[ -n "$isOcDbcontainer" ]]; then
+			echo "oc-db container is already running"
+		else
+      isCloseOcDbcontainer=$( docker ps -a -q -f name='oc-db' )
+      if [[ -n "$isCloseOcDbcontainer" ]]; then
+           echo "oc-db container starting..."
+          docker start oc-db
+          echo "oc-db container started"
+      else
+        isOcDBImage=$( docker images -q ${ocadmin_repo}/oc-db:${ocadmin_version} )
+        if [[ -n "$isOcDBImage" ]]; then
+          echo "oc-db container starting..."
+          docker start oc-db
+          sleep 10
+          echo "oc-db container started"
+        else
+          echo "### DOWNLOAD AND RUN \`oc-db\` START-UP SCRIPT..."
+          docker run --network logrhythm --env POSTGRES_PASSWORD=`date --rfc-3339=ns | md5sum | cut -c-32` --name oc-db --volume oc-db:/var/lib/postgresql/data --detach ${ocdb_repo}/oc-db:${ocdb_version}
+          sleep 10
+          echo "oc-db container started"
+        fi
+      fi
+		fi
+  else
+    echo "### Create \`oc-db\` Volume..."
+    docker volume create oc-db
+    echo "### DOWNLOAD AND RUN \`oc-db\` START-UP SCRIPT..."
+		docker run --network logrhythm --env POSTGRES_PASSWORD=`date --rfc-3339=ns | md5sum | cut -c-32` --name oc-db --volume oc-db:/var/lib/postgresql/data --detach ${ocdb_repo}/oc-db:${ocdb_version}
+    sleep 10
+    echo "oc-db container started"
+  fi
+}
+
+processStopOC_DB(){
+  #check oc-db container is up and runing or not
+  isOcAdmincontainer=$( docker ps -q -f name='oc-db' )
+  if [[ -n "$isOcAdmincontainer" ]]; 
+  then
+    echo "oc-db container stopping.."
+    docker stop oc-db
+    echo "oc-db container stopped"
+  else
+    echo "no oc-db container started"
+  fi
+}
+
+processRestartOC_DB(){
+  #check oc-db container is up and runing or not
+  isOcAdmincontainer=$( docker ps -q -f name='oc-db' )
+  if [[ -n "$isOcAdmincontainer" ]]; 
+  then
+      echo "oc-db container restart starting..."
+      #docker stop oc-db
+      docker restart oc-db
+      #cleanOcDbContainer
+      #cleanOcDbImages
+      #processStartOC_DB
+      echo "oc-db container restarted"
+  else
+      echo "no oc-db container started"
+  fi
+}
+
+processRestartOC_ADMIN(){
+  #check oc-admin container is up and runing or not
+  isOcAdmincontainer=$( docker ps -q -f name='oc-admin' )
+  echo "$isOcAdmincontainer"
+  if [[ -n "$isOcAdmincontainer" ]]; 
+  then
+      echo "oc-admin container restarting..."
+      #docker stop oc-admin
+      docker restart oc-admin
+      #cleanOcAdminContainer
+      #cleanOcAdminImages
+      #processStartOC_ADMIN
+      echo "oc-admin container restarted"
+  else
+      echo "no oc-admin container restarted"
+  fi
+}
+
+function checkOcAdminDataBase(){
+  #check oc-admin Database up and running or not
+  isDBAvailable=false
+  countUser=$( docker exec -i oc-db psql --username=postgres --dbname oc-admin -X -A -w -t -c "select count(*) from public.\"rbacUserToRole\";"  || true ) 2> /dev/null
+  if [[ -z "$countUser" ]]; 
+  then
+    isDBAvailable=false
+    echo "oc-admin database not available" 1>&2
+  else
+    if [[ "$countUser" > 0 ]];
+    then
+      isDBAvailable=true
+      echo "oc-admin database available"
+    else
+      isDBAvailable=false
+      echo "ocAdmin user not available"
+    fi
+  fi
+
+  #if data base not available so create oc-admin DB
+  if $isDBAvailable 
+  then
+    echo "oc-admin database available"
+  else
+    echo "oc-admin database is not present"
+    initializingOcDB start
+    sleep 10
+  fi 
+}
+
+processStartOC_ADMIN(){
+  #check oc-db container is up and runing or not
+  isOcDBcontainer=$( docker ps -q -f name='oc-db' )
+  if [[ -n "$isOcDBcontainer" ]];
+  then
+    #check oc-admn container is up and runing or not
+    isOcAdmincontainer=$( docker ps -q -f name='oc-admin' )
+    if [[ -n "$isOcAdmincontainer" ]]; then
+      echo "oc-admin container is already running"
+    else
+      #check oc-admn container is available or not
+      isCloseOcAdmincontainer=$( docker ps -a -q -f name='oc-admin' )
+      if [[ -n "$isCloseOcAdmincontainer" ]]; then
+        echo "oc-admin container is starting..."
+        docker start oc-admin
+        echo "oc-admin container started"
+      else
+        #check oc-admin image available or not
+        isOcAdminImage=$( docker images -q ${ocadmin_repo}/oc-admin:${ocadmin_version} )
+        if [[ -n "$isOcAdmincontainer" ]]; 
+        then
+          echo "oc-admin container is starting..."
+          docker start oc-admin
+          echo "oc-admin container started"
+        else
+          echo "### RUN \`oc-admin\` CONTAINER..."
+          docker run --detach --publish 8400:8400/tcp --network logrhythm --name oc-admin ${ocadmin_repo}/oc-admin:${ocadmin_version}
+          sleep 10
+        fi
+      fi
+      sleep 10
+      #check oc-admin data base exits or not
+      checkOcAdminDataBase
+      echo "oc-admin container started"
+    fi
+  else
+    echo "oc-db container is not running. Please start oc-db container first"
+  fi
+}
+
+resetAdminUser(){
+  
+  #check oc-admin Database up and running or not
+  isDBAvailable=false
+  countUser=$( docker exec -i oc-db psql --username=postgres --dbname oc-admin -X -A -w -t -c "select count(*) from public.\"rbacUserToRole\";"  || true )
+  if [[ -z "$countUser" ]]; 
+  then
+    isDBAvailable=false
+    echo "oc-admin database not available" 1>&2
+  else
+    if [[ "$countUser" > 0 ]];
+    then
+      isDBAvailable=true
+      echo "oc-admin database available"
+    else
+      isDBAvailable=false
+      echo "oc-admin user not available"
+    fi
+  fi
+
+  #if data base not available so create oc-admin DB
+  if $isDBAvailable 
+  then
+    initializingOcDB restart
+  else
+    echo "Either oc-admin database not available or ocAdmin user not available"
+  fi   
+  echo "New password set"
+}
+
+processStopOC_ADMIN(){
+  isOcAdmincontainer=$( docker ps -q -f name='oc-admin' )
+  echo "$isOcAdmincontainer"
+  
+  if [[ -n "$isOcAdmincontainer" ]]; 
+  then
+      echo "oc-admin container is stopping..."
+      docker stop oc-admin
+      echo "oc-admin container stopped"
+  else
+      echo "no oc-admin container stopped"
+  fi
+}
+
+helpFunction(){
+      echo ""
+      echo "Options:"
+      echo "   --help                     Shows this help"
+      echo "   oc-db start                Start oc-db container"
+      echo "   oc-db stop                 Stop oc-db container"
+      echo "   oc-db restart              Restart oc-db container"
+      echo "   oc-admin start             Start oc-admin container"
+      echo "   oc-admin stop              Stop oc-admin container"
+      echo "   oc-admin restart    	  Restart oc-admin container"
+      echo "   oc-admin resetAdminUser    resetAdminUser oc-admin container"
+      echo ""
+}
+# === EZ OC END ===
 # === MAIN PROCESSING ===
 
 # Create a new file handler (3) which will be used for the this script's
@@ -618,6 +1063,7 @@ fi
 while (("$#")); do
   case "${1}" in
     "--lrctl-debug")
+      echo ${1}
       lrctl_debug=$(($lrctl_debug + 1))
       shift 1
       ;;
@@ -672,6 +1118,7 @@ case "${first_non_flag_arg:-}" in
     getScriptVersion
     ;;
   *)
+  
     # Check if args has autoupdate and no dev flag. Skip condition if it does.
     if [[ "${args[@]}" != *"autoupdate"* && "${args[@]}" != *"--dev"* ]]; then
       updateScript
@@ -688,7 +1135,49 @@ case "${first_non_flag_arg:-}" in
         pullLrctlImage
       fi
     fi
-    # Run the lrctl in the container
-    runLrctl "${args[@]}"
+
+     # Run the lrctl in the container
+    if [ "${args[0]}" == "oc-db" ] || [ "${args[0]}" == "oc-admin" ] 
+      then
+        if [ "${args[0]}" == "oc-db" ]
+          
+          then
+            case ${args[1]} in
+              #case 1
+              "--help") helpFunction ;;
+
+              #case 2
+              "start") processStartOC_DB ;;
+                
+              #case 3
+              "stop") processStopOC_DB ;;
+
+              #case 4
+              "restart") processRestartOC_DB ;;
+
+            esac
+        fi
+        if [ "${args[0]}" == "oc-admin" ]
+          then
+            case ${args[1]} in
+              #case 1
+              "--help") helpFunction ;;
+
+              #case 2
+              "start") processStartOC_ADMIN ;;
+                
+              #case 3
+              "stop") processStopOC_ADMIN ;;
+
+              #case 4
+              "restart") processRestartOC_ADMIN ;;
+
+              #case 5
+              "resetadminuser") resetAdminUser ;;
+            esac
+        fi 
+      else
+        runLrctl "${args[@]}" 
+    fi
     ;;
 esac
