release 2021.02

diff --git a/lrctl b/lrctl
--- a/lrctl
+++ b/lrctl
@@ -8,7 +8,7 @@ script_name=$(basename "${BASH_SOURCE[0]}")
 # === LRCTL VARIABLES ===
 
 lrctl_debug=0
-lrctl_version="6.2.3"
+lrctl_version="6.2.4"
 lrctl_image=""
 lrctl_new_shell_after_group_membership=1
 lrctl_docker_membership_return_code=255
@@ -433,10 +433,21 @@ updateScript() {
     return 0
   fi
 
+  # Attempt to curl the updated lrctl script from the prod URL
+  # If the curl returns a non-zero exit code, fail
   local temp_file="${BASH_SOURCE[0]}_temp"
   curl --silent --fail "${prod_script_file_url}" > "${temp_file}"
   if [[ $? -ne "0" ]]; then
     echo "Failed to fetch ${prod_script_file_url}."
+    rm -f "${temp_file}"
+    return 1
+  fi
+  
+  # Check in ${temp_file} for "lrctl_version=" key
+  # If the grep returns a non-zero exit code, fail
+  grep -w --silent "lrctl_version=" "${temp_file}"
+  if [[ $? -ne "0" ]]; then
+    echo "Malformed LRCTL file downloaded from ${prod_script_file_url}."
     rm -f "${temp_file}"
     return 1
   fi
